fix - verbose bundle size output is no longer [object Object]
IjzerenHein/react-native-bundle-visualizer pull request #97
Opened 2022-11-30 16:24 UTC by omerg

This fixes the console output of individual file stats when verbose parameter is provided. Prior to the change, size of a file was not printed correctly:

Before:
`[sourceMappingURL], size: [object Object] bytes`

After:
`[sourceMappingURL], size: 35 bytes`

2022-12-10 21:30 UTC, hurali97 requested changes
Thanks for your PR, highly appreciated 🚀 If you could address the requested change, that would be so great 👍🏻

2022-12-11 11:24 UTC, IjzerenHein commented
Fixes #73

2022-12-16 23:51 UTC, omerg commented on src/react-native-bundle-visualizer.js
> +            chalk.green(file + ', size: ' + stats.size + ' bytes')
No problem @hurali97 , here is the change: https://github.com/IjzerenHein/react-native-bundle-visualizer/pull/97/commits/430886b8cadaebe4d829203f767f6fcb37078cbd

2022-12-19 11:09 UTC, hurali97 commented
@omerg Thanks for addressing changes. I notice CI is failing due to node 12 not supporting the optional chaining. Can you re-address and remove the optional chaining operator (?), like so:

Previously:
`chalk.green(file + ', size: ' + bundle.files[file]?.size + ' bytes')`

Now:
`chalk.green(file + ', size: ' + bundle.files[file].size + ' bytes')`

2022-12-20 19:09 UTC, omerg commented
> @omerg Thanks for addressing changes. I notice CI is failing due to node 12 not supporting the optional chaining. Can you re-address and remove the optional chaining operator (?), like so:
> 
> Previously: `chalk.green(file + ', size: ' + bundle.files[file]?.size + ' bytes')`
> 
> Now: `chalk.green(file + ', size: ' + bundle.files[file].size + ' bytes')`

Thanks for flagging @hurali97 , chaining operator is removed now 👍

2022-12-21 11:41 UTC, merged